trigger:
- main

pool:
  vmImage: 'Linux'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  displayName: 'Build and Publish'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd back
      npm install
    displayName: 'Install backend dependencies'

  - script: |
      cd front
      npm install
      npm run build
    displayName: 'Build frontend'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'frontend/build'
      artifactName: 'drop'
    displayName: 'Publish frontend artifacts'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure subscription 1'
      appName: 'testeito'
      package: $(Pipeline.Workspace)/drop
      deploymentMethod: 'zipDeploy'
      appType: 'webApp'
    displayName: 'Azure App Service Deploy'
